url_shortener/models.py
import string
from random import choices
from datetime import datetime
from itsdangerous.url_safe import URLSafeTimedSerializer as Serializer
from flask import current_app
from flask_login import UserMixin
from .extensions import db, login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    verified = db.Column(db.Boolean, default=False)
    password = db.Column(db.String(60), nullable=False)
    user_id = db.Column(db.String(60), nullable=False)
    user_token = db.Column(db.String(2000))
    admin = db.Column(db.Boolean)
    linkUser = db.relationship('Link', backref='author', lazy=True)

    def get_verification_token(self, expires_sec=180):
        s = Serializer(current_app.config['SECRET_KEY'], expires_sec)
        return s.dumps({'user_id': self.id}).decode('utf-8')

    @staticmethod
    def verify_verification_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            user_id = s.loads(token)['user_id']
        except:
            return None
        return User.query.get(user_id)

    def get_reset_token(self, expires_sec=180):
        s = Serializer(current_app.config['SECRET_KEY'], expires_sec)
        return s.dumps({'user_id': self.id}).decode('utf-8')

    @staticmethod
    def verify_reset_token(resetoken):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            user_id = s.loads(resetoken)['user_id']
        except:
            return None
        return User.query.get(user_id)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}')"


class Link(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    original_url = db.Column(db.String(2000))
    domain_url = db.Column(db.String(2000))
    title_url = db.Column(db.String(2000))
    short_url = db.Column(db.String(5), unique=True)
    visits = db.Column(db.Integer, default=0)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    location = db.Column(db.String(10000))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.short_url = self.generate_short_link()

    def generate_short_link(self):
        characters = string.digits + string.ascii_letters
        short_url = ''.join(choices(characters, k=5))

        link = self.query.filter_by(short_url=short_url).first()
        if link:
            return self.generate_short_link()

        def __repr__(self):
            return f"Links('{self.links}')"

        return short_url

url_shortener/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError, Regexp
from .models import User


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[
                           DataRequired(), Length(min=8, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Regexp(
        regex="(?=.*?[A-Z])", message='Password requires at least one uppercase character!'), Length(min=8, max=20)])
    confirm_password = PasswordField('Confirm Password', validators=[
                                     DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('Username is taken!')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Email is already registered!')


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Log In')


class RequestResetForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError(
                'There is no account with that email, you must register first!')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired(),
                                                     Regexp(
                                                         regex="(?=.*?[A-Z])", message='Password requires at least one uppercase character!'),
                                                     Length(min=8, max=20)])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Reset Password')

url_shortener/__init__.py
import os
from dotenv import load_dotenv
from flask import Flask
import url_shortener.routes
from .extensions import db, login_manager, bcrypt, api, mail

load_dotenv()

appF = Flask(__name__)
appF.config['SQLALCHEMY_DATABASE_URI'] = os.getenv("DATABASE_URL")

appF.config['SECRET_KEY'] = os.getenv("SECRET_KEY")
appF.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
appF.config['MAIL_SERVER'] = 'smtp.gmail.com'
appF.config['MAIL_PORT'] = 587
appF.config['MAIL_USE_TLS'] = True
appF.config['MAIL_USE_SSL'] = False

appF.config['MAIL_USERNAME'] = os.getenv("MAIL_USERNAME")
appF.config['MAIL_PASSWORD'] = os.getenv("MAIL_PASSWORD")
appF.config['MAIL_DEFAULT_SENDER'] = "spArrow@gmail.com"

appF.register_blueprint(url_shortener.routes.app)

db.init_app(appF)
bcrypt.init_app(appF)
api.init_app(appF)
mail.init_app(appF)

login_manager.init_app(appF)
login_manager.login_view = 'app.login'
login_manager.login_message_category = 'info'

url_shortener/auth.py
from functools import wraps
from flask import request, Response, current_app


def check_auth(username, password):
    '''This function is called to check if a username/
    password combination is valid.
    '''
    return username == current_app.config['ADMIN_USERNAME'] and password == current_app.config['ADMIN_PASSWORD']


def authenticate():
    '''Send a 401 response that enables basic auth'''
    return Response(
        'Could not verify your access level for that URL.\n'
        'You have to login with proper credentials', 401,
        {'WWW-Authenticate': 'Basic realm="Login Required"'}
    )


def require_auth(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        auth = request.authorization
        if not auth or not check_auth(auth.username, auth.password):
            return authenticate()
        return f(*args, **kwargs)
    return decorated

url_shortener/routes.py
import flask
import socket
import string
import urllib
import json
import random
from urllib.parse import quote
import validators
import tldextract
import requests
from sqlalchemy import asc, desc, and_, or_
from flask_mail import Message
from flask_login import login_user, current_user, logout_user, login_required
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort
import url_shortener.REST
from .forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm
from .models import User, Link
from .extensions import db, bcrypt, api, admin_USERID, mail


app = Blueprint('app', __name__)


def checkPrimaryAdmin():
    if current_user.user_id in admin_USERID:
        current_user.admin = True
        db.session.commit()


@app.route("/")
@app.route("/home")
def home():
    if current_user.is_authenticated:
        pass
    return render_template('home.html')


@app.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('app.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        letters = string.ascii_letters
        userID = ''.join(random.choice(letters) for i in range(10))
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password, user_id=userID)
        db.session.add(user)
        db.session.commit()
        send_verification_email(user)
        flash('Please verify your email before attempting to log in!', 'success')
        return redirect(url_for('app.login'))
    return render_template('register.html', title='Register', form=form)


@app.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        checkPrimaryAdmin()
        return redirect(url_for('app.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        try:
            if user.verified is not True:
                flash('Login Unsuccessful, please verify your email!', 'danger')
                return redirect(url_for('app.login'))
            if user and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('app.home'))
            else:
                flash(
                    'Login Unsuccessful, please check username and password!', 'danger')
        except:
            flash('Login Unsuccessful, please check username and password!', 'danger')
    return render_template('login.html', title='Login', form=form)


@app.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('app.home'))


@app.route('/<short_url>')
def redirect_to_url(short_url):
    link = Link.query.filter_by(short_url=short_url).first_or_404()
    teleDevice = flask.request.headers.get('User-Agent')
    url = 'http://ip-api.com/json/{}'.format(get_client_ip(flask.request))
    userLocation = requests.get(url).json()
    if userLocation['status'] == 'success':
        city = userLocation['city']
        country = userLocation['country']
        # print(city, country)
        if link.location is not None:
            old_dict = json.loads(link.location)
            # print(old_dict)
            try:
                old_dict["city"][city] = int(old_dict["city"][city]) + 1
            except:
                old_dict["city"][city] = 1
            try:
                old_dict["country"][country] = \
                    int(old_dict["country"][country]) + 1
            except:
                old_dict["country"][country] = 1
            print(old_dict)
            link.location = json.dumps(old_dict)
        else:
            new_dict = {"city": {city: 1}, "country": {country: 1}}
            new_dict_json = json.dumps(new_dict)
            link.location = new_dict_json
    else:
        pass
    link.visits = link.visits + 1
    db.session.commit()
    return redirect(link.original_url)


def get_client_ip(flaskRequest):
    if flaskRequest.headers.getlist("X-Forwarded-For"):
        ip = flaskRequest.headers.getlist("X-Forwarded-For")[0]
    else:
        ip = flaskRequest.remote_addr
    return ip


@app.route('/add_link', methods=['POST'])
@login_required
def add_link():
    checkPrimaryAdmin()
    original_url = request.form['original_url']
    if not validators.url(original_url):
        flash('Please insert a valid url', 'danger')
        return redirect(url_for('app.home'))
    checkLink = Link.query.filter(and_(Link.original_url == str(original_url),
                                       Link.user_id == current_user.id)).first()
    if checkLink:
        # Link exists in the database before
        flash('You have created this link before', 'info')
        return redirect(url_for('app.link_page', short=checkLink.short_url))
    ext = tldextract.extract(original_url)
    Domain = ext.domain
    url = "https://textance.herokuapp.com/title/" + quote(original_url)
    response = requests.get(url)
    if response.status_code != 200:
        title = "Unknown Title"
    else:
        title = str(response.content.decode("utf-8"))
    link = Link(original_url=original_url,
                domain_url=Domain, title_url=title, user_id=current_user.id)
    db.session.add(link)
    db.session.commit()
    return redirect(url_for('app.link_page', short=link.short_url))


@app.route('/stats')
@login_required
def stats():
    checkPrimaryAdmin()
    thisUser = User.query.filter_by(user_id=current_user.user_id).first()
    links = Link.query.filter_by(author=current_user).order_by(Link.id).all()
    return render_template('stats.html', links=links)


@app.route('/add_link/<short>', methods=['GET', 'POST'])
def link_page(short):
    link = Link.query.filter_by(short_url=short).first()
    # print(link.location)
    try:
        clickDict = json.loads(link.location)
        cityList = sorted(clickDict["city"].items(),
                          key=lambda item: item[1])[::-1]
        countryList = sorted(
            clickDict["country"].items(), key=lambda item: item[1])[::-1]
        # print(cityList, countryList)
        f5City = cityList[:5]
        f5Country = countryList[:5]
        # print(clickDict)
        cityKeys, cityValues, countryKeys, countryValues = [], [], [], []
        for i in range(min(5, len(f5City))):
            cityKeys.append(f5City[i][0])
            cityValues.append(f5City[i][1])
        for i in range(min(5, len(f5Country))):
            countryKeys.append(f5Country[i][0])
            countryValues.append(f5Country[i][1])
        #print(cityKeys, cityValues, countryKeys, countryValues)
    except:
        cityKeys, cityValues = [], []
        countryKeys, countryValues = [], []

    return render_template('link_added.html',
                           new_link=link.short_url, original_url=link.original_url, link=link,
                           cityKeys=cityKeys, cityValues=cityValues, countryKeys=countryKeys, countryValues=countryValues)


@app.errorhandler(404)
def page_not_found(e):
    return '<h1>404</h1>', 404


@app.route('/admin/<userID>')
@login_required
def admin(userID):
    checkPrimaryAdmin()
    if current_user.admin is not True:
        flash('You have no access to this page', 'danger')
        return redirect(url_for('app.home'))
    users = User.query.order_by(User.id).all()
    return render_template('admin.html', users=users,
                           primaryAdmin=admin_USERID[0], currentUser=current_user)


@app.route('/admin/<userID>', methods=['POST'])
@login_required
def setAdmin(userID):
    checkPrimaryAdmin()
    changedUserID = request.form['submit_button']
    changedUser = User.query.filter_by(user_id=changedUserID).first()
    changedUser.admin = not changedUser.admin
    db.session.commit()
    return redirect(url_for('app.setAdmin', userID=userID))


@app.route("/add_link/delete", methods=['POST'])
@login_required
def delete_link():
    checkPrimaryAdmin()
    link_id = request.form['delete_button']
    link = Link.query.get_or_404(link_id)
    if link.author != current_user:
        abort(403)
    db.session.delete(link)
    db.session.commit()
    flash('Link has been deleted!', 'success')
    return redirect(url_for('app.stats'))


@app.route("/graph")
@login_required
def global_graph():
    checkPrimaryAdmin()

    # global
    links = Link.query.all()
    dictionary = {}
    for link in links:
        try:
            dictionary[link.domain_url] += link.visits
        except:
            dictionary[link.domain_url] = link.visits
    len_dict = len(dictionary)
    sum_dict = sum(dictionary.values())
    dictionary = dict(
        reversed(sorted(dictionary.items(), key=lambda item: item[1])))
    dictionary = dict(list(dictionary.items())[:5])
    dictionary = json.dumps(dictionary)

    # current User
    userLinks = Link.query.filter_by(author=current_user).all()
    currentDictionary = {}
    for link in userLinks:
        try:
            currentDictionary[link.domain_url] += link.visits
        except:
            currentDictionary[link.domain_url] = link.visits
    len_curdict = len(currentDictionary)
    sum_curdict = sum(currentDictionary.values())
    currentDictionary = dict(
        reversed(sorted(currentDictionary.items(), key=lambda item: item[1])))
    currentDictionary = dict(list(currentDictionary.items())[:5])
    currentDictionary = json.dumps(currentDictionary)

    # COUNTRY DATA
    clink = Link.query.filter_by(author=current_user).all()
    cityDict = {}
    countryDict = {}
    # clink will prduce a list [..., ...]
    for link in clink:
        try:
            clickDict = json.loads(link.location)
            cityList = sorted(

url_shortener/templates/graph.html
{% extends "layout.html" %}
{% block content %}
<div class="chart-container">
  <canvas id="chart"></canvas>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
<script>
  var jsDomainURL = [];
  var jsVisits = [];
  {% for inlink in link %}
    jsDomainURL.push("{{inlink.domain_url}}");
    jsVisits.push( {{inlink.visits}} );
  {% endfor %}
  var data = {
    labels  :jsDomainURL,
    datasets: [{
              label: "Most visited sites globally",
              backgroundColor: "rgba(255,99,132,0.2)",
              borderColor: "rgba(255,99,132,1)",
              borderWidth: 2,
              hoverBackgroundColor: "rgba(255,99,132,0.4)",
              hoverBorderColor: "rgba(255,99,132,1)",
              data : jsVisits,
    }]
  };

  var options = {
    maintainAspectRatio: false,
    scales: {
      yAxes: [{
        stacked: true,
        gridLines: {
          display: true,
          color: "rgba(255,99,132,0.2)"
        }
      }],
      xAxes: [{
        gridLines: {
          display: false
        }
      }]
    }
  };


  Chart.Bar('chart', {
    options: options,
    data: data
  });
</script>
{% endblock content%}

url_shortener/templates/index.html
<form method='POST' action="{{ url_for('short.add_link') }}">
    <input type="text" name="original_url">
    <input type="submit">
</form>

url_shortener/templates/layout.html
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script>
            let vh = window.innerHeight*0.01;
            document.documentElement.style.setProperty('--vh', `${vh}px`);
            var myScreenOrientation = window.screen.orientation;
            myScreenOrientation.lock("portrait");
        </script>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <!-- <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'> -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">
        <!--<link rel="stylesheet" href="{{ url_for('static', filename='cssgraph.css') }}">-->
        <!-- <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='trythis.css')}}"> -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='table.css')}}">
        <link rel="icon" href="{{ url_for('static', filename='logo/Sparrow (Logo, Dark, Trans).png') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        {% if title %}
        <title> URL Shortener - {{ title }} </title>
        {% else %}
        <title> URL Shortener</title>
        {% endif %}

        <script src="js/uikit.min.js"></script>
        <script src="js/uikit-icons.min.js"></script>
        
        <style>
            body{
                color: #D9DAD7;
                background-color: black;
            }
        </style>
        {% if title %}
        <title> URL Shortener - {{ title }} </title>
        {% else %}
        <title> URL Shortener</title>
        {% endif %}
    </head>
<!-- 
    <div id="stars"></div>
    <div id="stars2"></div>
    <div id="stars3"></div> -->

    <body style="position:fixed; width:100%;height:100%;background-color:transparent; margin:auto;">
        <div style="z-index: -5; overflow:visible; position:absolute; height:100%; width:100%; display:block;">
            <div id="stars"></div>
            <div id="stars2"></div>
            <div id="stars3"></div>
        </div>
        <div class="whole" style="overflow-y: auto; position:absolute; height:100%; width:100%" id="scrollDiv">       
            <header class="site-header">
                <nav>
                    <div class="leftSide">
                        <a class="urlLogo" href="/"><img class="logo" src="{{ url_for('static', filename='logo/Sparrow (Logo, Dark, Trans).png') }}"> <h3 style="text-transform:none">spArrow</h3></a>
                    </div>
                    <div>
                        {% if current_user.is_authenticated %}
                            <ul class="rightSide">
                            {% if current_user.admin == True %}
                                <li><a class="adminLogo" href="{{ url_for('app.admin', userID=current_user.user_id) }}">Admin</a></li>
                            {% endif %}
                                <li><a class="adminLogo" href="{{ url_for('app.home') }}">Home</a></li>
                                <li><a class="loginLogo" href="{{ url_for('app.stats') }}">List</a></li>
                                <li><a class="graphLogo" href="{{ url_for('app.global_graph') }}">Graph</a></li>
                                <li><a class="RegisterLogo" href="{{ url_for('app.logout') }}">Log Out</a></li>
                            </ul>
                        {% else %}
                        <ul class="rightSide">
                            <li><a class="loginLogo" href="{{ url_for('app.login') }}">Login</a></li>
                            <li><a class="RegisterLogo" href="{{ url_for('app.register') }}">Register</a></li>
                        </ul>
                        {% endif %}
                    </div>

                    
                    <!--Mobile config-->
                    <div class="burgerView">
                        <div class="top"></div>
                        <div class="mid"></div>
                        <div class="bottom"></div>
                    </div>
                </nav>
            </header>

            <span class="brSpace"></span>

            <main role="main" style="flex-wrap: nowrap; justify-content: center;">
                <div class="roow" style="margin:auto; position:relative; width:80%;">
                    {% with messages = get_flashed_messages(with_categories = true) %}
                        {% if messages %}
                            {%  for category, message in messages %}
                                <div class ="alert alert-{{ category }}" id="flashMessage">
                                    {{ message }}
                                </div>
                                <script>
                                    var flash = document.getElementById('flashMessage');
                                    setTimeout(PushDown, 250);
                                    function PushDown(){
                                        flash.classList.add("alertAfter");
                                        setTimeout(PushUp, 3000);
                                    }
                                    function PushUp(){
                                        flash.classList.remove("alertAfter");
                                    }
                                </script>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}
                </div>
            </main>
        </div>
        <!-- <span class="brSpace"></span> -->
        <script>
            if(!!window.performance && window.performance.navigation.type === 2){
                window.location.reload();}
        </script>
        <link rel='stylesheet' type="text/css" href="{{ url_for('static', filename='parallaxStar.css')}}">
        <script src="{{ url_for('static', filename='index.js')}}"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

url_shortener/templates/link_added.html
{% extends "layout.html" %}
{% block content %}
<style>
  #urlList:hover {
    color: red;
    cursor: pointer;
  }
</style>
<div class="moreInfoBackground" style="position:relative">
  <div class="midSection">
    <b style="color:white; font-weight: normal">Title:</b> <b style="color:white; font-weight: normal">{{ link.title_url }}</b>
    <br>
    <b style="font-weight: normal">Old Link:</b> <a id='OldLink' href="{{ original_url }}">{{ original_url }}</a>
    <br />
    <b style="font-weight: normal">New Link: </b> <a id='NewLink' href="{{ url_for('app.redirect_to_url', short_url=new_link, _external = True) }}">
        {{ url_for('app.redirect_to_url', short_url=new_link, _external = True) }}
    </a>
    <br />
    <canvas id="qr-code"></canvas>
    <br />
    {% if cityKeys|length > 0 %}
      <table class="tables">
        <tr>
          <th style= "width:300px">City</th>
          <th>Clicks</th>
        </tr>
        {% for i in range(cityKeys|length) %}
          <tr class="tablack">
            <th >{{ cityKeys[i] }}</th>
            <th>{{ cityValues[i] }}</th>
          </tr>
        {% endfor %}
      </table>
    {% endif %}
    <br />
    {% if countryKeys|length > 0 %}
      <table>
        <tr>
          <th style= "width:300px">Country</th>
          <th>Clicks</th>
        </tr>
        {% for i in range(cityKeys|length) %}
          <tr class="tablack">
            <th>{{ countryKeys[i] }}</th>
            <th>{{ countryValues[i] }}</th>
          </tr>
        {% endfor %}
      </table>
    {% endif %}
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/qrious/4.0.2/qrious.min.js"></script>
  <script>
      function urlListPage(){
        window.location.href = "{{ url_for('app.stats') }}"
      }

      var qrtext = document.getElementById("NewLink").textContent;
      var qr;
      (function() {
          qr = new QRious({
          element: document.getElementById('qr-code'),
          foreground: 'black',
          size: 200,
          value: qrtext,
          });
      })();
  </script>
        <br />
        <div class="backButDiv">
          <b class="backButton" id = "urlList" onclick="urlListPage()">&#x2190; URL List</b>
        </div>
        <br />
          {% if current_user %}
            <div class="midSection">
              <button type="button" class="backButton" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
          {% endif %}
    <!-- Modal -->
    <div class="modal " id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <b style="color: Black">Delete Link?</b>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <form action="{{ url_for('app.delete_link') }}" method="POST">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
              <button name="delete_button" class="btn btn-secondary" value="{{ link.id }}">Yes</button>
            </form>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock content%}

url_shortener/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section" style="display: flex; width: 500px; justify-content: center; margin: auto;">
    <form method="POST" action="" style="width:80%;">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="loginStyle">Login</legend>
            <!-- border-bottom mb-4 -->
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-light") }}
        </div>
            <small class="text-muted ml-2">
            <a href="{{ url_for('app.reset_request') }}">Forgot Password?</a>
        </small>
        <div class="border-top-light" >
            <small class="text-muted" style="width: 80%; margin:auto;">
                <mark style="color:white; background-color: transparent;">Don't have an account?</mark><a class="ml-2" href="{{ url_for('app.register') }}">Register</a>
            </small>
        </div>               
    </form>
</div>

{% endblock content %}